### ISSUE TITLE
Bugs 🐛

### ISSUE THREAD

**Issue by TayMcKenzieNZ** [Mathu-lmn/mth-rc#11]
- When RC explodes, blip still appears on map
- Can't self destruct unless out of RC camera view
- When you do /recall, RC gets close to you and then Franklin begins to insult you from it. 

Perhaps we can replace Franklin's voice lines with that of the mechanic saying "It's comin at ya!"

**Comment by Mathu-lmn** [comment]
All fixed on V1.0.4 !
